#   #################################
#   #  _   _      ______     _____  #
#   # | | | |     |  _  \   /  ___| #
#   # | |_| | __ _| | | |___\ `--.  #
#   # |  _  |/ _` | | | / _ \`--. \ #
#   # | | | | (_| | |/ /  __/\__/ / #
#   # \_| |_/\__,_|___/ \___\____/  #
#   #                               #
#   #################################
#   #      Hannes Debian Setup      #
#   #           .xinitrc            #
#   #################################

# Start AwesomeWM
setxkbmap -option caps:swapescape
setxkbmap -option altwin:swap_alt_win
exec awesome
